services:
  postgres:
    build: .
    environment:
      POSTGRES_USER: ejemplo
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: electromobility
    ports:
      - "5432:5432"
    volumes:
      - db-data:/db-data
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ejemplo@ejemplo.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "5050:80"
    depends_on:
      - postgres
volumes:
  db-data: